name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'Dockerfile'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Java for backend
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      # Setup Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
      
      # Create Artifact Registry repository (if not exists)
      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create clean-connect-repo \
            --repository-format=docker \
            --location=us-central1 \
            --description="Clean Connect Docker repository" || true
      
      # Configure Docker for GCP
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/clean-connect-a80a2/clean-connect-repo/clean-connect-backend .
      
      # Push Docker image
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/clean-connect-a80a2/clean-connect-repo/clean-connect-backend
      
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy clean-connect-backend \
            --image=us-central1-docker.pkg.dev/clean-connect-a80a2/clean-connect-repo/clean-connect-backend \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --port=8080 \
            --memory=512Mi \
            --service-account=clean-connect-app@clean-connect-a80a2.iam.gserviceaccount.com